#!/usr/bin/env python3
from __future__ import annotations

import argparse
import collections
import re
import sys
from pathlib import Path


FAMILY_MAP = {
    "Steering_Angle": "DISC_SIG_STEERING",
    "Engine_Speed": "DISC_SIG_RPM",
    "Throttle_Position": "DISC_SIG_THROTTLE",
    "Accelerator_Pedal_Position": "DISC_SIG_THROTTLE",
    "Gear": "DISC_SIG_GEAR",
    "Brake_Position": "DISC_SIG_BRAKE",
    "Brake_Pedal_Position": "DISC_SIG_BRAKE",
    "Brake_Pressure": "DISC_SIG_BRAKE",
}

SG_RE = re.compile(
    r'^ SG_\s+([^ :]+)\s*:\s*(\d+)\|(\d+)@(\d)([+-])\s*'
    r'\(([^,]+),([^)]+)\)\s*\[([^|]+)\|([^\]]+)\]\s*"([^"]*)"'
)
BO_RE = re.compile(r"^BO_\s+(\d+)\s+[^:]+:\s+(\d+)")


def signal_enum(name: str) -> str | None:
    if name in FAMILY_MAP:
        return FAMILY_MAP[name]
    if name.startswith("Brake_Position") or name.startswith("Brake_Pressure"):
        return "DISC_SIG_BRAKE"
    if name.startswith("Wheel_Speed_") or name.startswith("Indicated_Vehicle_Speed_"):
        return "DISC_SIG_WHEEL_SPEED"
    return None


def c_string(value: str) -> str:
    raw = value.encode("utf-8", errors="replace")
    out: list[str] = ['"']
    for b in raw:
        if b == 0x22:
            out.append(r"\"")
        elif b == 0x5C:
            out.append(r"\\")
        elif 0x20 <= b <= 0x7E:
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02X}")
    out.append('"')
    return "".join(out)


def parse_dbcs(dbcs_dir: Path):
    support = collections.Counter()

    for path in sorted(dbcs_dir.glob("*.dbc")):
        current_can_id: int | None = None
        current_dlc: int | None = None
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            bo = BO_RE.match(line)
            if bo:
                current_can_id = int(bo.group(1))
                current_dlc = int(bo.group(2))
                continue

            if current_can_id is None or current_dlc is None:
                continue

            sg = SG_RE.match(line)
            if not sg:
                continue

            name = sg.group(1).strip()
            sig_enum = signal_enum(name)
            if sig_enum is None:
                continue

            key = (
                sig_enum,
                current_can_id,
                current_dlc,
                int(sg.group(2)),
                int(sg.group(3)),
                int(sg.group(4)),
                sg.group(5),
                name,
                sg.group(6).strip(),
                sg.group(7).strip(),
                sg.group(8).strip(),
                sg.group(9).strip(),
                sg.group(10),
            )
            support[key] += 1

    rows = []
    for key, count in support.items():
        rows.append((*key, count))

    rows.sort(
        key=lambda r: (
            r[0],
            r[1],
            -r[13],
            r[3],
            r[4],
            r[7],
        )
    )
    return rows


def emit_header(rows) -> str:
    lines = [
        "/* Auto-generated by tools/gen_can_discover_priors.py. */",
        "/* Do not edit manually; regenerate from the dbcs directory. */",
        "#ifndef CAN_DISCOVER_PRIORS_H",
        "#define CAN_DISCOVER_PRIORS_H",
        "",
        "static const disc_dbc_prior_t s_dbc_priors[] = {",
    ]

    for row in rows:
        (
            sig_enum,
            can_id,
            dlc,
            start_bit,
            bit_length,
            byte_order,
            sign_char,
            name,
            factor,
            offset,
            min_val,
            max_val,
            unit,
            support_count,
        ) = row

        lines.append(
            "    { %s, %du, %uu, %d, %d, %d, '%s', %s, %s, %s, %s, %s, %s, %d },"
            % (
                sig_enum,
                can_id,
                dlc,
                start_bit,
                bit_length,
                byte_order,
                sign_char,
                c_string(name),
                c_string(factor),
                c_string(offset),
                c_string(min_val),
                c_string(max_val),
                c_string(unit),
                support_count,
            )
        )

    lines.extend(
        [
            "};",
            "",
            "#define DISC_DBC_PRIOR_COUNT ((int)(sizeof(s_dbc_priors) / sizeof(s_dbc_priors[0])))",
            "",
            "#endif",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate embedded can_discover DBC priors from dbcs/*.dbc."
    )
    parser.add_argument("dbcs_dir", nargs="?", default="dbcs")
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output header path, or - for stdout",
    )
    args = parser.parse_args()

    dbcs_dir = Path(args.dbcs_dir)
    if not dbcs_dir.is_dir():
        parser.error(f"DBC directory not found: {dbcs_dir}")

    header = emit_header(parse_dbcs(dbcs_dir))
    if args.output == "-":
        sys.stdout.write(header)
    else:
        Path(args.output).write_text(header, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
